// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAh2qIkSVyzj9dyonqraDs6q3HsXycdGY',
    appId: '1:266608057433:web:eb918dbb530d9e093c6548',
    messagingSenderId: '266608057433',
    projectId: 'eventapp-56b78',
    authDomain: 'eventapp-56b78.firebaseapp.com',
    storageBucket: 'eventapp-56b78.firebasestorage.app',
    measurementId: 'G-C7GFPWXQFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt5KfVYPD_BYSPKVw_W155BqlqAz5sRA8',
    appId: '1:266608057433:android:371f7a54832ef6943c6548',
    messagingSenderId: '266608057433',
    projectId: 'eventapp-56b78',
    storageBucket: 'eventapp-56b78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb9fXDMLbZZjCnZhrHb7qnEK0YASwzFAI',
    appId: '1:266608057433:ios:c4e49dab5e6505e73c6548',
    messagingSenderId: '266608057433',
    projectId: 'eventapp-56b78',
    storageBucket: 'eventapp-56b78.firebasestorage.app',
    iosBundleId: 'com.example.eventapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb9fXDMLbZZjCnZhrHb7qnEK0YASwzFAI',
    appId: '1:266608057433:ios:c4e49dab5e6505e73c6548',
    messagingSenderId: '266608057433',
    projectId: 'eventapp-56b78',
    storageBucket: 'eventapp-56b78.firebasestorage.app',
    iosBundleId: 'com.example.eventapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAh2qIkSVyzj9dyonqraDs6q3HsXycdGY',
    appId: '1:266608057433:web:4c85a35ef788d5e73c6548',
    messagingSenderId: '266608057433',
    projectId: 'eventapp-56b78',
    authDomain: 'eventapp-56b78.firebaseapp.com',
    storageBucket: 'eventapp-56b78.firebasestorage.app',
    measurementId: 'G-4W1981P8F6',
  );
}
